### ISSUE TITLE
Wrong version of chromedriver installed after Chrome update

### ISSUE THREAD

**Issue by dmurdoch** [ropensci/binman#7]
My system recently auto-updated to Chrome 89.0.4389.90, and RSelenium stopped being able to open it.  After some debugging, I found that chromedriver 89.0.4389.23 was installed into `~/Library/Application Support/binman_chromedriver/mac64/89.0.4389.23`, but when I went to that directory and ran it, I saw this error:

```
$ ./chromedriver --version
-bash: ./chromedriver: Bad CPU type in executable
```

The directory also held `chromedriver_mac64_m1.zip` and `chromedriver_mac64.zip`.  I don't have an M1 chip in my laptop, so I unzipped the 2nd one to replace the chromedriver file, and now things are working again.

I'm assuming by the directory name it was `binman` that unpacked the wrong zip.  I'd be happy to run other tests if you want to track this down, but for now my system is fixed.

**Comment by dmurdoch** [comment]
Just a note that the same thing happened today when my system updated to Chrome 91.0.x.y, and the same fix worked.

**Comment by dmurdoch** [comment]
And happened again today, but this time I found https://github.com/ropensci/wdman/pull/26, which fixes the issue.

**Comment by juyeongkim** [comment]
Merged https://github.com/ropensci/wdman/pull/26
