### ISSUE TITLE
Could not open Chrome Browser

### ISSUE THREAD

**Issue by speedreader** [ropensci/binman#8]
Similar to the issue above. Can't open Chrome (version 89.0.4389.xx) using RSelenium. I only have a chromedriver file for an M1 in the following folder:

/Users/blahblah/Library/Application Support/binman_chromedriver/mac64/89.0.4389.23

I'm not on an M1 Mac. Best I can tell, that's the root of the problem (see: "error=86, Bad CPU type in executable")

<img width="786" alt="Screenshot 2021-03-23 at 5 38 36 PM" src="https://user-images.githubusercontent.com/16739809/112228339-28a8bb00-8bff-11eb-92e8-e0ca8b1fecbd.png">

**Comment by juyeongkim** [comment]
Merged https://github.com/ropensci/wdman/pull/26
